### ISSUE TITLE
plugin not found after install !

### ISSUE THREAD

**Issue by mcarbonneaux** [svalgaard/certbot-dns-infoblox#2]
after installing the plugin with pip....
when start certbot they fail with this error:

```
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1328, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/disco.py", line 236, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/disco.py", line 251, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/disco.py", line 56, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'certbot_dns_infoblox.dns_infoblox'
```

**Comment by svalgaard** [comment]
You are right. The main Python file was actually installed in the wrong location. Could you try to upgrade to the latest release?
````
pip install --upgrade  certbot-dns-infoblox
````
If it does not work, please specify which OS + version you are using, e.g., Ubuntu 20.04. Thanks.

**Comment by svalgaard** [comment]
I'm closing the issue again. Please reopen, if you still have an issue.

**Comment by mcarbonneaux** [comment]
now it's work!
